on:
  push:
    paths-ignore:
      - DBT_Materializations.xlsx
      - DBT_Materializations.pkl

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  parse-materializations:
    name: Scan sql files materialization
    runs-on: ubuntu-latest

